services:
  - type: web
    name: autoclassjoiner-bot
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: REG_NUMBER
        sync: false
      - key: PASSWORD
        sync: false
      - key: NODE_ENV
        value: production
